[package]
name = "gfx_device_vulkanll"
version = "0.1.0"
description = "Vulkan (Low Level) backend for gfx-rs"
homepage = "https://github.com/gfx-rs/gfx"
repository = "https://github.com/gfx-rs/gfx"
keywords = ["graphics", "gamedev"]
license = "Apache-2.0"
authors = ["The Gfx-rs Developers"]
workspace = "../../.."

[lib]
name = "gfx_device_vulkanll"

[dependencies]
log = "0.3"
lazy_static = "0.2"
shared_library = "0.1"
gfx_corell = { path = "../../corell", version = "0.1.0" }
ash = "0.15.7"
spirv-utils = { git = "https://github.com/msiglreith/spirv-utils.git", branch = "gfx" }
winit = "0.7"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
