sudo: required
language: rust
rust:
  - stable
  - nightly
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7479b6691b7e5e40716a
    on_success: always
    on_failure: always
    on_start: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  apt:
    sources:
      # install a newer cmake since at this time Travis only has version 2.8.7
      - george-edison55-precise-backports
      # add a repository for libsdl2-dev (enable sudo before uncommenting this)
      - sourceline: 'ppa:zoogie/sdl2-snapshots'
    packages:
      - xdotool
      - cmake
      - cmake-data
      - libxxf86vm-dev
      - libxinerama-dev
      - libxinerama1
      - libxcursor-dev
      - libxcursor1
      - libsdl2-dev
script:
  - export RUST_BACKTRACE=1
  - cargo build --features vulkan
  - cargo test -p gfx_core
  - cargo test -p gfx
  - cargo test -p gfx_device_gl
  - cargo test -p gfx_window_glutin
  - cargo test -p gfx_window_glfw
  - cargo test -p gfx_window_sdl
  - cargo test -p gfx_device_vulkan --features vulkan
  - cargo test -p gfx_window_vulkan --features vulkan
  - cargo test --features vulkan
