sudo: false
language: rust
rust:
- stable
- beta
- nightly
before_script:
- pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7479b6691b7e5e40716a
    on_success: always
    on_failure: always
    on_start: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  apt:
    sources:
    # install a newer cmake since at this time Travis only has version 2.8.7
    - kalakris-cmake
    packages:
    - xdotool
    - cmake
    - libxxf86vm-dev
    - libxinerama-dev
    - libxinerama1
    - libxcursor-dev
    - libxcursor1
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc -- -j 1
after_success:
- travis-cargo --only nightly doc-upload
env:
  global:
  - secure: eYm18Lr7+FYFgY9Cj/LFyL0WaC/zesBE8pywho9c+ByUEMwaZ9QCbsaX3H+IBNQCTSCImiKj+zuj+uIPyOTIiC5OPY0cvziWcBvyAlrwnwT7oBm8X9CPDCuspRVGO52CoksI1oYNkEc1xaL9PIUw6GMXhVCAIkQI7tMbq+kWxDQ=
