environment:
  matrix:
    - TARGET: 1.19.0-x86_64-pc-windows
      COMPILER: gnu
    - TARGET: 1.19.0-x86_64-pc-windows
      COMPILER: msvc
    - TARGET: nightly-x86_64-pc-windows
      COMPILER: msvc
install:
  - if %COMPILER%==gnu choco install -y mingw
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}-${env:COMPILER}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin;C:\tools\mingw64\bin"
  - if %COMPILER%==gnu gcc -v
  - rustc -vV
  - cargo -vV
build_script:
  # No d3d12 support on GNU windows ATM
  # context: https://github.com/gfx-rs/gfx/pull/1417
  - if (%COMPILER%==gnu) {
    - >
      cargo build --all --features vulkan
      --exclude gfx_window_glfw
      --exclude gfx_device_metal
      --exclude gfx_device_metalll
      --exclude gfx_window_metal
      --exclude gfx_device_dx12ll
    } else {
      - >
        cargo build --all --features vulkan
        --exclude gfx_window_glfw
        --exclude gfx_device_metal
        --exclude gfx_device_metalll
        --exclude gfx_window_metal
    }
test_script:
  # re: gfx is gfx_render
  - cargo test -p gfx -p gfx_core
  - if (%COMPILER%==gnu) {
    - >
      cargo test --all --features vulkan
      --exclude gfx_window_glfw
      --exclude gfx_device_metal
      --exclude gfx_device_metalll
      --exclude gfx_window_metal
      --exclude gfx_device_dx12ll
    } else {
      - >
        cargo test --all --features vulkan
        --exclude gfx_window_glfw
        --exclude gfx_device_metal
        --exclude gfx_device_metalll
        --exclude gfx_window_metal
      - cargo test -p gfx -p gfx_core --features dx11
      - cargo test -p gfx -p gfx_core --features dx12
      - cargo test -p gfx -p gfx_core --features dx12ll
    }
