[package]
name = "gfx-examples"
version = "0.0.4"

[[bin]]
name = "cube"
path = "src/cube/main.rs"

[[bin]]
name = "deferred"
path = "src/deferred/main.rs"

[[bin]]
name = "glutin"
path = "src/glutin/main.rs"

[[bin]]
name = "performance"
path = "src/performance/main.rs"

[[bin]]
name = "terrain"
path = "src/terrain/main.rs"

[[bin]]
name = "triangle"
path = "src/triangle/main.rs"

[dependencies]
env_logger = "*"
gfx_gl = "*"
glfw = "*"
rand = "*"
time = "*"
genmesh = "*"
noise = "*"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
#version = "*"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"
#version = "*"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx_macros"
#version = "*"
plugin = true

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_macros"
#version = "*"

[dependencies.gfx_window_glutin]
git = "https://github.com/gfx-rs/gfx_window_glutin"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
