[workspace]

members = [
    "src/backend/dx12",
    "src/backend/empty",
    "src/backend/gl",
    "src/backend/metal",
    "src/backend/vulkan",
    "src/hal",
    "src/warden",
    "src/render",
    "examples/hal/quad",
    "examples/hal/compute",
    "examples/render/quad_render",
]
