[package]

name = "example-terrain"
version = "0.1.0"
authors = [
]

[[bin]]
name = "terrain"
path = "main.rs"

[dependencies.gfx]
path = "../../../"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.cgmath]
git = "http://github.com/bjz/cgmath-rs"

[dependencies.vertex]
git = "https://github.com/csherratt/vertex-rs.git"

[dependencies.noise-rs]
git = "https://github.com/bjz/noise-rs.git"
