[package]

name = "example-triangle"
version = "0.1.0"
authors = [
]

[[bin]]
name = "triangle"
path = "main.rs"

[dependencies.gfx]
path = "../../"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
