[package]

name = "example-triangle"
version = "0.1.0"
authors = [
]

[[bin]]
name = "triangle"
path = "main.rs"

[dependencies.gfx]
path = "../../../"

[dependencies.gl_init_platform]
path = "../../gl_init_platform"

[dependencies.glfw_platform]
path = "../../glfw_platform"
