[package]

name = "gl-init"
version = "0.1.0"
authors = [
]

[[bin]]
name = "gl-init"
path = "main.rs"

[dependencies.gfx]
path = "../../"

[dependencies.gl_init]
git = "https://github.com/tomaka/gl-init-rs.git"
