[package]

name = "glfw_platform"
version = "0.1.0"
authors = [
]

[[lib]]
name = "glfw_platform"
path = "lib.rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.device]
path = "../device/"
