[package]

name = "gl_init_platform"
version = "0.1.0"
authors = [
]

[[lib]]
name = "gl_init_platform"
path = "lib.rs"

[dependencies.gl_init]
git = "https://github.com/tomaka/gl-init-rs.git"

[dependencies.device]
path = "../device/"
