[package]
name = "gfx-backend-empty"
version = "0.1.0"
description = "Empty backend for gfx-rs"
publish = false
workspace = "../../.."

[lib]
name = "gfx_backend_empty"

[dependencies]
gfx-hal = { path = "../../hal", version = "0.1" }
